# Generated by Django 3.0.3 on 2021-03-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_and_authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
